blueprint:
  name: "[EMS] - [Car] - [Charging automation] - Morning Minimum"
  description: Makes sure that in the morning there is at least the minimum amount of battery in the car.
  domain: automation
  source_url: https://raw.githubusercontent.com/gsaurer/ha-ems/main/blueprints/EMS/EMS-Car-Charging-MorningMin.yaml
  input:
    ems_enabled:
      name: EMS - Enabled
      description:
        Switch that defines if the Energy Managment system should be turned
        on. It's the main switch for your EMS systm. If you don't have one create
        a new one directly in the blueprint. Turning it off this will disable this
        automation.
      selector:
        entity:
          domain:
            - input_boolean
          multiple: false
    ems_charging_type:
      name: Charging type
      description:
        This defines which type of charging should be used - Potential
        values of this entity are (Default, Surplus, Trip, Stop). If you don't have
        this entity create it directly in the blueprint and add it to your it to your
        dashboard to select what charging type you want.
      selector:
        entity:
          filter:
            - domain:
                - input_select
          multiple: false
    ems_charger_phases:
      name: Charger - Phase switch mode
      description:
        Defines if the charger is using single phase for charging. At the
        moment only Single phase is supported for Surplus but it will set it back
        to 3-phase charging for other Types (e.g. Default & Trip)
      selector:
        entity:
          filter:
            - domain:
                - select
          multiple: false
    ems_charger_current:
      name: Charger - Requested current
      description: The current value of the charger
      selector:
        entity:
          filter:
            - domain:
                - number
          multiple: false
    ems_charger_forced_state:
      name: Charger - Forced state
      description:
        Defines the forced state of the charger - wether it is Neutral
        or it should start charging.
      selector:
        entity:
          filter:
            - domain:
                - select
          multiple: false
    ems_car_battery_percentage_now:
      name: Car - Battery percentage
      description: The current battery level of the car
      selector:
        entity:
          filter:
            - device_class:
                - battery
            - domain:
                - sensor
          multiple: false
    ems_car_min_morning_battery:
      name: Car - Minimum morning battery percentage
      description:
        The minimum battery percentage in the morning to start the day.
        If the battery is below this value the automation will make sure the battery
        has at lest the % configured here in the morning even the setting is set to
        surplus charging.
      default: 15
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: "%"
          step: 1.0
          mode: slider
variables: []

trigger:
  - platform: time_pattern
    at: "21:00:00"
condition:
  - condition: state
    entity_id: !input ems_enabled
    state: "on"
  - condition: state
    entity_id: !input ems_charging_type
    state: Surplus
action:
  - variables:
      maxCurrentToCharge: "{{ 16 }}"
  - choose:
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: !input ems_car_battery_percentage_now
            above: 0
            below: !input ems_car_min_morning_battery
        alias: Morning minimum
    sequence:
      - service: select.select_option
        metadata: {}
        data:
          option: Auto
        target:
          entity_id: !input ems_charger_phases
        alias: Set charging phases to Auto
      - service: number.set_value
        metadata: {}
        data:
          value: "{{ maxCurrentToCharge }}"
        target:
          entity_id: !input ems_charger_current
        alias: Set Current
      - service: select.select_option
        metadata: {}
        data:
          option: Neutral
        target:
          entity_id: !input ems_charger_forced_state
        alias: Start charging
mode: single
