blueprint:
  name: "[EMS] - [Car] - [Charging automation] - [Trip] - Calendar entry"
  description: This script works in conjunction with the other automations. It checks the calendar for entries with a specific value and based on that set's the charging to a trip to make sure a certain battery % is reached. 
  domain: automation
  source_url: https://raw.githubusercontent.com/gsaurer/ha-ems/main/blueprints/EMS/EMS-Car-Charging-Trip-Calendar.yaml
  input:
    #general settings
    ems_enabled:
      name: EMS - Enabled
      description: Switch that defines if the Energy Managment system should be turned on. It's the main switch for your EMS systm. If you don't have one create a new one directly in the blueprint. Turning it off this will disable this automation.
      selector:
        entity:
          domain: input_boolean
    ems_charging_type:
      name: Charging type
      description: This defines which type of charging should be used - Potential values of this entity are (Default, Surplus, Trip, Stop). If you don't have this entity create it directly in the blueprint and add it to your it to your dashboard to select what charging type you want.
      selector:
        entity:
          filter:
            domain: input_select
    ems_charger_power_max:
      name: Charger - Power max
      description: The maximum kWh per hour the charger can load the car with
      selector:
        entity:
          filter:
          - domain:
            - input_number
          multiple: false

    #calendar settings
    ems_calendar:
      name: Calendar
      description: The calendar that should be used rgulary for entries with the <Tag> to make sure the car is fully charged before you have to leave.
      selector:
        entity:
          filter:
            domain: calendar
    ems_calendar_tag:
      name: Calendar entry Tag
      description: The tag that needs to be included in the calendar entry to makre it as an event for charging
      default: "EMS-Charging"
      selector:
        text:
    ems_calendar_nextstart_datetime:
      name: Calendar - Next charging start time
      description: Entity that holds the next start time for calendar charging. This is optional but will help you to check when charging strats.
      selector:
        entity:
          filter:
            - domain: input_datetime

    # car settings
    ems_car_battery_percentage_now:
      name: Car - Battery percentage - now
      description: The current battery level of the car
      selector:
        entity:
          filter:
            - device_class: battery
            - domain: sensor
    ems_car_battery_percentage_charging_limit:
      name: Car - Battery percentage - charging limit
      description: The entity that can set the battery charging limit
      selector:
        entity:
          filter:
            - device_class: battery
            - domain: number
    ems_car_battery_percentage_trip:
      name: Car - Battery percentage - Trip
      description: Helper entity that holds the percentage that should be charged to for a trip (max 100 (%))
      selector:
        entity:
          filter:
            - domain: input_number
    ems_car_battery_power_max:
      name: Car - Battery power max
      description: The maximum power of the battery in kWh
      selector:
        entity:
          filter:
            - domain: input_number

    #otehrs
    #ems_notification_service:
    #  name: Notification service to use
    #  description: Notification service to send a note when charging has started
    #  selector:
    #    action:

variables:
  ems_calendar: !input ems_calendar
  ems_calendar_tag: !input ems_calendar_tag
  ems_car_battery_percentage_now: !input ems_car_battery_percentage_now
  ems_car_battery_percentage_trip: !input ems_car_battery_percentage_trip
  ems_car_battery_power_max: !input ems_car_battery_power_max
  ems_charger_power_max: !input ems_charger_power_max

trigger:
  - platform: time_pattern
    minutes: /10
condition:
  - condition: state
    entity_id: !input ems_enabled
    state: "on"
action:
  - service: calendar.get_events
    target:
      entity_id: !input ems_calendar
    data:
      duration:
        hours: 24
        minutes: 0
        seconds: 0
    response_variable: events
  - repeat:
      sequence:
        - if:
            - condition: template
              value_template: " {{ ems_calendar_tag in repeat.item['summary'] }}"
          then:
            - variables:
                chargingPercentPerHour: >-
                  {{ 100 / (states(ems_car_battery_power_max) | int / states(ems_charger_power_max)|int) }}
                chargingPercentMissing: >-
                  {{states(ems_car_battery_power_trip)|float
                  -
                  states(ems_car_battery_percentage_now)|float(100)
                  }}
                minToFinish: >-
                  {{ ((chargingPercentMissing / chargingPercentPerHour) * 60) |
                  int }}
                tripDate: "{{ repeat.item['start']|as_datetime }}"
                timeToStart: >-
                  {{ repeat.item['start']|as_datetime - timedelta( minutes =
                  minToFinish+15) }}
            - service: input_datetime.set_datetime
              target:
                entity_id: !input ems_calendar_nextstart_datetime
              data:
                datetime: "{{timeToStart}}"
            - alias: Check to change Charging Limit (Surplus enablement) - This is done to make sure we use sun the sun more bebefore we travel.
              if:
                - condition: template
                  value_template: >-
                    {{ states(ems_charging_type) == "Surplus" }}
                  alias: Check if Surplus is set
                - condition: template
                  value_template: "{{ tripDate|as_datetime < now() + timedelta( hours = 15) }}"
                  alias: Check if Trip is starting in less than 15h
              then:
                - service: number.set_value
                  metadata: {}
                  data:
                    value: >-
                      {{ states(ems_car_battery_percentage_trip)|float }}
                  target:
                    entity_id: !input ems_car_battery_percentage_charging_limit
            - alias: Check to change Charging for Trip
              if:
                - condition: template
                  value_template: >-
                    {{ states(ems_charging_type) != "Trip" }}
                  alias: Check if Trip is already on
                - condition: template
                  value_template: >-
                    {{ timeToStart|as_datetime < now() + timedelta( minutes =
                    10) }}
              then:
                - service: input_select.select_option
                  metadata: {}
                  data:
                    option: Trip
                  target:
                    entity_id: !input ems_charging_type
                  enabled: true
                - service: notify.signal_me
                  data:
                    title: "[EMS] - Trip - Charging"
                    message: >-
                      [EMS] Changed Charging to load for Trip {{
                      repeat.item['summary'] }} at {{
                      repeat.item['start']|as_datetime|
                      timestamp_custom('%H:%M') }}. Current battery state is {{
                      states(ems_car_battery_percentage_now) }}%.
                      {{ chargingPercentMissing }}% will be charged in {{
                      minToFinish }} minutes.
      for_each: "{{ events[ems_calendar].events }}"
mode: single
