blueprint:
  name: "[EMS] - [Car] - [Charging automation] - Type changed"
  description:
    This automation adopts the settings of the go-e charger accordingly
    after a specific charging type has been selected. Supported Types are (Default,
    Surpluse, Trip and Stop)
  domain: automation
  source_url: https://raw.githubusercontent.com/gsaurer/ha-ems/main/blueprints/EMS-Car-Charging-TypeChanged.yaml
  input:
    ems_enabled:
      name: EMS - Enabled
      description:
        Switch that defines if the Energy Managment system should be turned
        on. It's the main switch for your EMS system. Turning this switch off will
        disable this automation.
      selector:
        entity:
          domain:
            - input_boolean
          multiple: false
    ems_charging_type:
      name: Charging type
      description:
        This defines which type of charging should be used - Potential
        values of this entity are (Default, Surplus, Trip, Stop). If you don't have
        this entity create it directly in the blueprint and add it to your it to your
        dashboard to select what charging type you want.
      selector:
        entity:
          filter:
            - domain:
                - input_select
          multiple: false
    ems_car_battery_percentage_now:
      name: Car - Battery percentage now
      description: The current battery level of the car
      selector:
        entity:
          filter:
            - device_class:
                - battery
            - domain:
                - sensor
          multiple: false
    ems_car_battery_percentage_charging_limit:
      name: Car - Battery percentage charging limit
      description: The entity that defines the the battery charging limit
      selector:
        entity:
          filter:
            - device_class:
                - battery
            - domain:
                - number
          multiple: false
    ems_car_battery_percentage_default:
      name: Car - Battery percentage for default
      description:
        Helper entity that holds the percentage that should be charged
        to for a trip (e.g. 80 (%))
      selector:
        entity:
          filter:
            - domain:
                - input_number
          multiple: false
    ems_car_battery_percentage_trip:
      name: Car - Battery percentage for trip
      description:
        Helper entity that holds the percentage that should be charged
        to for a trip (max 100 (%))
      selector:
        entity:
          filter:
            - domain:
                - input_number
          multiple: false
    ems_charger_current:
      name: Charger - Requested current
      description: The current value of the charger
      selector:
        entity:
          filter:
            - domain:
                - number
          multiple: false
    ems_charger_phases:
      name: Charger - Phase switch mode
      description:
        Defines if the charger is using single phase for charging. At the
        moment only Single phase is supported for Surplus but it will set it back
        to 3-phase charging for other Types (e.g. Default & Trip)
      selector:
        entity:
          filter:
            - domain:
                - select
          multiple: false
    ems_charger_logic_mode:
      name: Charger - Logic mode
      description:
        Defines the logic mode of the charger - wether it is Default or
        Eco mode.
      selector:
        entity:
          filter:
            - domain:
                - select
          multiple: false
    ems_charger_forced_state:
      name: Charger - Forced state
      description:
        Defines the forced state of the charger - wether it is Neutral
        or it should start charging.
      selector:
        entity:
          filter:
            - domain:
                - select
          multiple: false
    ems_charger_current_default:
      name: Carger - Default curent
      description: The default current that should be used
      default: 14
      selector:
        number:
          min: 0.0
          max: 32.0
          unit_of_measurement: A
          mode: slider
          step: 1.0
    ems_charger_current_surplus:
      name: Carger - Surplus curent
      description: The default current that should be used
      default: 6
      selector:
        number:
          min: 0.0
          max: 32.0
          unit_of_measurement: A
          mode: slider
          step: 1.0
    ems_charger_current_trip:
      name: Charger - Trip current
      description: The trip current that should be used
      default: 16
      selector:
        number:
          min: 0.0
          max: 32.0
          unit_of_measurement: A
          mode: slider
          step: 1.0
variables:
  ems_charging_type: !input ems_charging_type
  ems_car_battery_percentage_default: !input ems_car_battery_percentage_default
  ems_car_battery_percentage_trip: !input ems_car_battery_percentage_trip
  ems_charger_current: !input ems_charger_current
  ems_charger_current_default: !input ems_charger_current_default
  ems_charger_current_surplus: !input ems_charger_current_surplus
  ems_charger_current_trip: !input ems_charger_current_trip
trigger:
  - platform: state
    entity_id: !input ems_charging_type
  - platform: time
    at: 06:00:00
condition:
  - condition: state
    entity_id: !input ems_enabled
    state: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input ems_charging_type
            state: Default
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Default
            target:
              entity_id: !input ems_charger_logic_mode
          - service: select.select_option
            metadata: {}
            data:
              option: Neutral
            target:
              entity_id: !input ems_charger_forced_state
          - service: select.select_option
            metadata: {}
            data:
              option: Auto
            target:
              entity_id: !input ems_charger_phases
            alias: Set charging phases to Auto
          - service: number.set_value
            metadata: {}
            data:
              value: "{{ ems_charger_current_default }}"
            target:
              entity_id: !input ems_charger_current
            alias: Set Current
          - service: number.set_value
            enabled: false
            continue_on_error: true
            metadata: {}
            data:
              value: "{{ states(ems_car_battery_percentage_default)|int(0) }}"
            target:
              entity_id: !input ems_car_battery_percentage_charging_limit
      - conditions:
          - condition: state
            entity_id: !input ems_charging_type
            state: Surplus
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Eco mode
            target:
              entity_id: !input ems_charger_logic_mode
          - service: select.select_option
            metadata: {}
            data:
              option: Neutral
            target:
              entity_id: !input ems_charger_forced_state
          - service: select.select_option
            metadata: {}
            data:
              option: Force single phase
            target:
              entity_id: !input ems_charger_phases
            alias: Set charging phases to Auto
          - service: number.set_value
            metadata: {}
            data:
              value: "{{ ems_charger_current_surplus }}"
            target:
              entity_id: !input ems_charger_current
            alias: Set Current
          - service: number.set_value
            enabled: false
            continue_on_error: true
            metadata: {}
            data:
              value: "{{ states(ems_car_battery_percentage_default)|int(0) }}"
            target:
              entity_id: !input ems_car_battery_percentage_charging_limit
      - conditions:
          - condition: state
            entity_id: !input ems_charging_type
            state: Trip
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Default
            target:
              entity_id: !input ems_charger_logic_mode
          - service: select.select_option
            metadata: {}
            data:
              option: Neutral
            target:
              entity_id: !input ems_charger_forced_state
          - service: select.select_option
            metadata: {}
            data:
              option: Auto
            target:
              entity_id: !input ems_charger_phases
            alias: Set charging phases to Auto
          - service: number.set_value
            metadata: {}
            data:
              value: "{{ ems_charger_current_trip }}"
            target:
              entity_id: !input ems_charger_current
            alias: Set Current
          - service: number.set_value
            enabled: false
            continue_on_error: true
            metadata: {}
            data:
              value: "{{ states(ems_car_battery_percentage_trip)|int(0) }}"
            target:
              entity_id: !input ems_car_battery_percentage_charging_limit
      - conditions:
          - condition: state
            entity_id: !input ems_charging_type
            state: Morning-Min
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Default
            target:
              entity_id: !input ems_charger_logic_mode
          - service: select.select_option
            metadata: {}
            data:
              option: Neutral
            target:
              entity_id: !input ems_charger_forced_state
          - service: select.select_option
            metadata: {}
            data:
              option: Auto
            target:
              entity_id: !input ems_charger_phases
            alias: Set charging phases to Auto
          - service: number.set_value
            metadata: {}
            data:
              value: "{{ ems_charger_current_trip }}"
            target:
              entity_id: !input ems_charger_current
            alias: Set Current
          - service: number.set_value
            enabled: false
            continue_on_error: true
            metadata: {}
            data:
              value: "{{ states(ems_car_battery_percentage_trip)|int(0) }}"
            target:
              entity_id: !input ems_car_battery_percentage_charging_limit        
      - conditions:
          - condition: state
            entity_id: !input ems_charging_type
            state: Stop
        sequence: []
mode: single
